# Generated by Django 5.2.17 on 2026-10-09 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('job_description', models.TextField(blank=True, default='')),
                ('resume', models.TextField(blank=True, default='')),
                ('predicted_questions', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='Applied', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoryBankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('situation', models.TextField(blank=True, default='')),
                ('task', models.TextField(blank=True, default='')),
                ('action', models.TextField(blank=True, default='')),
                ('result', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='avg_wpm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='session_type',
            field=models.CharField(default='Live Interview', max_length=50),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='total_fillers',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InterviewDebrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=0)),
                ('executive_summary', models.TextField(blank=True, default='')),
                ('question_reviews', models.JSONField(blank=True, default=list)),
                ('thank_you_email_draft', models.TextField(blank=True, default='')),
                ('follow_up_questions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debrief', to='api.interviewsession')),
            ],
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='job_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='api.jobapplication'),
        ),
    ]
